# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Seo For Life
email: davidmcneal28@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is SEO for ...life
baseurl: / # the subpath of your site if applicable, e.g. /blog
url: "https://seofor.life" # the base hostname & protocol for your site, e.g. https://example.com

# Permalink format (/blog/ is ignored for pages)
permalink: /blog/:title

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

collections:
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
  
# set some common post defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name
      comments: true
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      search: true
      sidebar: home_sidebar
      topnav: topnav
      tooltip: true
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      section: "page" # set the root section name
      search: true
      sidebar: home_sidebar
      topnav: topnav
      tooltip: true


# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - filename.md
  - subfolder_name/
  - mydoc_*
  - gitignore


repository: davidmcneal28/thecryptowriter

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

github_editme_path: davidmcneal28/thecryptowriter/blob/gh-pages/

topnav_title: Seo For . . Life
# this appears on the top navigation bar next to the home button

site_title: Seo For Life
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: SeoFor.Life
# this appears in the footer

# github_editme_path: 

# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

# gitlab_editme_path: tomjoht/documentation-theme-jekyll/blob/gh-pages/
# if you're using GitLab, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

google_analytics: 
# if you have google-analytics ID, put it in. if not, edit this value to blank.

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor

#  these are the files and directories that jekyll will exclude from the build

feedback_subject_line: Feedback

feedback_email: davidmcneal28@gmail.com

# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

feedback_link: "https://seofor.life"
# if you uncomment the previous line, it changes where the feedback link points to

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: false
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

sidebars:
- home_sidebar
- mydoc_sidebar
- product1_sidebar
- product2_sidebar
- other

# the description is used in the feed.xml file

github: [metadata]
